Resources:
  LambdaSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    DeletionPolicy: Retain
    Properties:
      GroupName: !Sub "${self:service}-lambda-sg-${AWS::Region}"
      GroupDescription: Allow all outbound traffic, no inbound
      SecurityGroupIngress:
        - IpProtocol: -1
          CidrIp: 127.0.0.1/32
      VpcId: ${self:custom.config.vpcId}
      Tags:
        - Key: 'adsk:moniker'
          Value: ${self:custom.config.moniker}
